apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: care-fe-production-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: care-fe-production-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 90