apiVersion: apps/v1
kind: Deployment
metadata:
  name: care-production-celery-beat
spec:
  template:
    metadata:
      labels:
        name: care-production-celery-beat
        app: care-production-celery-beat
        env: production
        namespace: default
    spec:
#      imagePullSecrets:
#        - name: githubreg
      containers:
        - name: care
          image: ghcr.io/coronasafe/care:production-latest
          imagePullPolicy: Always
          # resources:
          #   requests:
          #     memory: "200Mi"
          #     cpu: "100m"
          #   limits:
          #     memory: "300Mi"
          #     cpu: "100m"
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "/app/celery_beat.sh" ]
          envFrom:
            - configMapRef:
                name: care-production
            - secretRef:
                name: care-production
          env:
            - name: RESTART_
              value: "20200331015742"
            - name: deployment-version
              value: "_BUILD_NUMBER_"
          volumeMounts:
            - name: newrelic-ini
              mountPath: /etc/newrelic.ini
              subPath: newrelic.ini
              readOnly: true
      volumes:
        - name: newrelic-ini
          secret:
            secretName: care-production
            defaultMode: 0444
            items:
              - key: NEWRELIC_INI
                path: newrelic.ini
  selector:
    matchLabels:
      app: care-production-celery-beat
