apiVersion: v1
kind: ConfigMap
metadata:
  name: care-production
  labels:
    app: care
    env: production
    namespace: default
data:
  POSTGRES_DB: 'care'
  POSTGRES_USER: 'postgres'
  POSTGRES_HOST: 'hostname'
  POSTGRES_PORT: '5432'
  DJANGO_SETTINGS_MODULE: 'config.settings.production'
  DJANGO_SECURE_SSL_REDIRECT: 'False'
  USE_S3: 'False'
  AWS_STORAGE_BUCKET_NAME: ''
  CSRF_TRUSTED_ORIGINS: '["care-django-production", "care.demo.example.in", "careapi.demo.example.in"]'
  DJANGO_ALLOWED_HOSTS: '["care-django-production", "care.demo.example.in", "careapi.demo.example.in"]'
  RATE_LIMIT: "5/10m"
  MAINTENANCE_MODE: "0"
  CLOUD_PROVIDER: "GCP"
  CLOUD_REGION: "asia-south1"
